name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  syntax:
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@18fcb8e3e06b4247c676c506750dc95ea7226479 # 2026.07.13.1

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
